### ISSUE TITLE
update LDP-Service and check all conformance tests 

### ISSUE THREAD

**Issue by m-alreeni** [enilink/enilink#17]

**Comment by kenwenzel** [comment]
@m-alreeni Is this issue fixed?

**Comment by m-alreeni** [comment]
@kenwenzel  
all automated  test cases in W3C LDP Test Suite passed. but some requirements or recommendations must be tested manually. It is difficult or impossible to write automated tests for and is not part of the testsuite. these special tests are skipped. only a part of the test report was includded because the complete report is so long. the included report referes to these skipped tests but the reasons are in the complete report  as follwing example: 

<html>
<body>
<h2 style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a id="org.w3.ldp.testsuite.test.MemberResourceTest_testRestrictClientInference">MemberResource-RestrictClientInference</a></h2>

[SKIPPED TEST]
--
This requirement or recommendation must be tested manually. It is difficult or impossible to write automated tests for and is not part of the testsuite.

<p style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">How to Run testRestrictClientInference</p><ul style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li>Perform a GET on a URL for the reource requesting an RDF content type</li><li>Inspect the results (both headers and content) for missing terms. Additionally could run an inferencing tool and compare results, seeing if needed informationshould have been explicitly listed by the server.</li></ul>
</body>
</html>

**Comment by m-alreeni** [comment]
@kenwenzel 
I think that this issue can be closed  if you don't mind
